spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;database=project_management_db;trustServerCertificate=true
    username: sa
    password: 12345

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update