spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;database=project_management_db;trustServerCertificate=true
    username: sa
    password: 12345

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  mail:
      host: smtp.gmail.com
      port: 587
      username: --enter your email to test send email
      password: --enter your email password to test send email
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true